---
env:
  node: true
parser: '@typescript-eslint/parser'
extends:
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.eslint.json
rules:
  '@typescript-eslint/array-type':
    - error
    - default: generic
  '@typescript-eslint/interface-name-prefix':
    - error
    - never
  '@typescript-eslint/explicit-function-return-type': 'off'
overrides:
  - files:
      - src/**/*.test.ts
    env:
      node: true
      jest: true
  - files:
      - '*.js'
    rules:
      '@typescript-eslint/no-var-requires': 'off'
